var header = "";
header += '<nav class="navbar navbar-expand-md navbar-dark">';
header += '  <div class="container-fluid">';
header += '    <a class="navbar-brand" href="index.html"><img src="img/logo-wt.png" alt="けんごウェブテクノロジー"></a>';
header += '    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span>';
header += '    </button>';
header += '    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">';
header += '      <ul class="navbar-nav">';
header += '        <li class="nav-item active"><a href="#sec1" class="nav-link">OUR VISION</a></li>';
header += '        <li class="nav-item"><a href="#sec2" class="nav-link">MENU</a></li>';
header += '        <li class="nav-item"><a href="#sec3" class="nav-link">STAFF</a></li>';
header += '      </ul>';
header += '    </div>';
header += '  </div>';
header += ' </nav>';
document.getElementById('headerinject').innerHTML = header;
var header = "";
footer += ' <div class="container py-5">';
footer += '   <div id="footer-contents" class="row mb-5">';
footer += '     <div class="col-lg-6 col-xl-8">';
footer += '       <address class="col-lg-10 offset-lg-1 mb-0">';
footer += '         <p class="footer-ttl">会社概要</p>';
footer += '         <p>けんごウェブテクノロジー</p>';
footer += '         <p>岐阜県岐阜市加納村松町１−４０</p>';
footer += '         <p>Tel: 携帯持ってません</p>';
footer += '         <p>Email: info@kwtechno.com</p>';
footer += '         <p>Fax: ファックス持ってません</p>';
footer += '       </address>';
footer += '     </div>';
footer += '     <div id="footer-news" class="col-lg-6 col-xl-4">';
footer += '       <div class="col-lg-10 offset-lg-1">';
footer += '         <p class="footer-ttl">NEWS</p>';
footer += '         <ul>';
footer += '           <li><span>2020.05.27</span>ページ作成しました。</li>';
footer += '         </ul>';
footer += '       </div>';
footer += '     </div>';
footer += '   </div><!-- .row -->';
footer += ' </div><!-- .container -->';
footer += ' <div id="copyright">';
footer += '   <p class="text-center mb-0 pt-3 pb-3">&copy;&ensp;けんごウェブテクノロジー All Rights Reserved.</p>';
footer += ' </div><!-- .container-fluid -->';
